# Generated by Django 4.1.7 on 2024-09-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='slug',
            new_name='url',
        ),
    ]
